apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv   
spec:
  storageClassName: manual     
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /db
---  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
spec:
  storageClassName: manual      
  accessModes:
     - ReadWriteOnce
  resources:
    requests: 
      storage: 3Gi 
